
theme: jekyll-theme-minimal
title: 1st Workshop on New IP and Beyond
avatar: "assets/img/icnp_logo.svg"
description: "Research, Innovation and Experimentation<br/>
of Internet Protocol Evolutions<br/>
for Future and Emerging Applications<br/>
<br/>
kiranm@futurewei.com"
logo: assets/img/icnp_logo.svg
