
theme: jekyll-theme-minimal
title: 1st Workshop on New IP and Beyond
description:  Research, Innovation and Experimentation of Internet Protocol Evolutions for Future and Emerging Applications
avatar: "/assets/img/icnp_logo.svg"
